version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    branches:
      ignore:
        - gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:df:26:dd:c7:a0:73:64:f6:98:81:c9:cc:1f:5d:df"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Update Documentation
          shell: /bin/sh
          command: |
              if [ "${CIRCLE_BRANCH}" != "develop" ];
                then
                echo "Only build documentation on develop branch"
                exit 0;
              fi

              git init
              git config --global user.name "Mauricio Cousillas"
              git config --global user.email "mauricio.cousillas@moove-it.com"
              git remote add upstream "git@github.com:moove-it/pw-ui.git"
              git fetch upstream && git reset --hard
              npm install
              npm run storybook:build

              git add -f docs/*
              git add .gitignore
              git stash
              git clean -fdx
              git rm -rf .
              git stash apply
              git mv docs/* .
              git clean -fdx

              touch .
              git add -A -f .
              git commit -m "Updated documentation"
              git push -f upstream HEAD:gh-pages




