version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    branches:
      ignore:
        - gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c7:b1:04:1f:d4:2c:1d:61:0a:a3:1f:cc:3a:ff:19:a0"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Update Documentation
          shell: /bin/sh
          command: |
              if [ "${CIRCLE_BRANCH}" != "develop" ];
                then
                echo "Only build documentation on develop branch"
                exit 0;
              fi
              git init
              git config --global user.name "Mauricio Cousillas"
              git config --global user.email "mauricio.cousillas@moove-it.com"
              git remote add upstream "git@github.com:moove-it/pw-ui.git"
              git fetch upstream && git reset --hard
              npm install
              npm run storybook:build
              git add .
              git commit -m "Updated documentation"
              git push -f upstream HEAD:gh-pages




